# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: OpenLawLibrary.TAF
PackageVersion: 0.35.5
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
